DEBUG 2016-06-16 11:11:10,185: 	 Executing command: 'kill'
DEBUG 2016-06-16 11:11:10,186: 	 Found CRAB cache file /home/georgemm01/.crab3
ERROR 2016-06-16 11:11:10,189: 	 Error: crab_jobs/crabcrab_CRAB3_Small_Output_Brazos_16061610121 is not a valid CRAB project directory.
ERROR 2016-06-16 11:11:10,189: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 254, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 62, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 563, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_jobs/crabcrab_CRAB3_Small_Output_Brazos_16061610121 is not a valid CRAB project directory.
DEBUG 2016-06-16 11:11:36,826: 	 Executing command: 'kill'
DEBUG 2016-06-16 11:11:36,827: 	 Found CRAB cache file /home/georgemm01/.crab3
ERROR 2016-06-16 11:11:36,830: 	 Error: crab_jobs/crabcrab_CRAB3_Small_Output_Brazos_160616101216 is not a valid CRAB project directory.
ERROR 2016-06-16 11:11:36,831: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 254, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 62, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1606/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 563, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_jobs/crabcrab_CRAB3_Small_Output_Brazos_160616101216 is not a valid CRAB project directory.
DEBUG 2016-11-15 15:39:06,522: 	 Executing command: 'status'
DEBUG 2016-11-15 15:39:06,523: 	 Found CRAB cache file /home/georgemm01/.crab3
DEBUG 2017-01-10 10:13:15,078: 	 Executing command: 'status'
DEBUG 2017-01-10 10:13:15,079: 	 Found CRAB cache file /home/georgemm01/.crab3
